[workspace]

members = [
    "async_await", # stlib future + crate futures + tokio with async/await
    "futures",     # crate futures 0.1
    "stdlib",      # only stdlib primitives
    "tokio"        # crate tokio 0.1
]

# todo worspaces async/await, tokio, actix and so on
